export const ui = {
  auth: {
    eyebrow: "Sign in",
    title: "Access your profile or explore in preview mode.",
    automaticSignInHeading: "Preparing your account...",
    automaticSignInTitle: "Automatic sign-in",
    automaticSignInBody:
      "Your session is opening automatically. Give it a moment.",
    readyTitle: "Account access is ready",
    setupTitle: "Account access is still being set up",
    readyBody: "Sign in with email and password or create a new account.",
    setupBody:
      "Backend access is not configured yet. Preview mode is still available.",
    missingDetailsTitle: "Missing details",
    missingDetailsBody: "Enter both your email and password.",
    accountCreatedTitle: "Account created",
    accountCreatedBody:
      "Your account is ready. Check your email if verification is required.",
    signInErrorTitle: "Sign-in error",
    genericError: "Something went wrong.",
    emailLabel: "Email",
    emailPlaceholder: "name@email.com",
    passwordLabel: "Password",
    passwordPlaceholder: "At least 8 characters",
    signIn: "Sign in",
    createAccount: "Create account",
    working: "Working...",
    continueInPreview: "Continue in preview",
  },
  welcome: {
    eyebrow: "ToneMatch",
    title: "Find your best colors, then turn them into real outfit decisions.",
    body:
      "Use a selfie to map undertone and contrast, discover the colors that suit you most, and shape your wardrobe around them.",
    highlightsTitle: "What you can do with ToneMatch",
    highlights: [
      "Build a personal palette from one selfie",
      "Get clothing and color recommendations that suit you",
      "Manage your wardrobe with clearer rules",
    ],
    howItWorksTitle: "How it works",
    howItWorksBody:
      "Capture a selfie, generate your color profile, then explore outfit guidance shaped around it. Every step is designed to respect privacy.",
    continueWithAccount: "Continue with your account",
    previewMode: "Preview mode",
    startExploring: "Start exploring now",
  },
  analysisLoading: {
    inProgressMessage: "Analysis is still in progress...",
    failedPill: "ANALYSIS FAILED",
    completePill: "COMPLETE",
    analyzingPill: "ANALYZING PROFILE",
    errorTitle: "Something went wrong",
    readyTitle: "Analysis complete!",
    workingTitle: "Defining your palette",
    errorBody: "Could not complete analysis. Please try again.",
    readyBody: "We are opening your report now.",
    workingBody:
      "Our AI is mapping your undertone, contrast, and color direction.",
    goBack: "Go Back",
    progressLabel: "Overall Progress",
    footerNote:
      "We process the scan privately and keep the wait short. Most reports land in under 15 seconds.",
    steps: [
      "Analyzing skin undertones",
      "Evaluating facial contrast",
      "Matching seasonal palette colors",
      "Curating personalized recommendations",
    ],
  },
  analysisResult: {
    header: "ANALYSIS REPORT",
    signatureOverline: "YOUR SIGNATURE PALETTE",
    whyHeading: "WHY THIS WORKS FOR YOU",
    whyLink: "SEE HOW IT WORKS",
    closeSecondMatch: "CLOSE SECOND MATCH",
    secondGuide: "OPEN 2ND STYLE GUIDE",
    secondOccasion: "OPEN 2ND OCCASION GUIDE",
    bestOnYou: "Best on you",
    primaryTones: "PRIMARY TONES",
    useWithCare: "Use with care",
    coolTones: "COOL TONES",
    openStyleGuide: "OPEN STYLE GUIDE",
    openOccasionGuide: "OPEN OCCASION GUIDE",
    shopYourTones: "SHOP YOUR TONES",
  },
} as const;
